[issue/108] - Add notification by sending successful the database
teamulster2/soTired pull request #112
Opened 2021-09-23 10:01 UTC by diehmlukas

- Add Singleton to notifications.dart
close #108

2021-09-23 18:00 UTC, mac641 requested changes
Found some typos and an issue within the singleton design pattern.
Perhaps, this also fixes your notification appearance bug 🤔

2021-09-23 18:02 UTC, mac641 commented on app/lib/notifications/notifications.dart
> +  factory Notifications() => _notificationsInstance;
Oh okay, I haven't noticed the missing `?` on the instance, so you can ignore this suggestion ;)

2021-09-25 13:34 UTC, mac641 approved these changes
Let's get this merged ^^

2021-09-27 07:55 UTC, treilik approved these changes

2021-09-27 07:59 UTC, merged