Issue/97 - Adjust database adapter for server
teamulster2/soTired pull request #113
Opened 2021-09-27 14:46 UTC by mac641

closes #97

2021-09-28 10:42 UTC, treilik requested changes
would you please change the sending of emojis to descriptive english words so that a change of emojis does not change the server client protokoll :smile:

2021-09-28 11:32 UTC, treilik approved these changes

2021-09-28 15:39 UTC, diehmlukas approved these changes
Looks good to me. :+1:

2021-09-28 21:09 UTC, treilik submitted a review, later dismissed

2021-09-29 07:32 UTC, diehmlukas approved these changes

2021-09-29 12:46 UTC, treilik approved these changes

2021-09-29 12:46 UTC, merged