[issue/7] - added motivation part
teamulster2/soTired pull request #29
Opened 2021-08-30 14:19 UTC by AnnaGsell

- Installation and Usage chapters are missing,
because they can better be added in the end

2021-08-30 14:29 UTC, diehmlukas approved these changes

2021-08-30 15:38 UTC, mac641 requested changes
Just two minor things ;)

2021-08-30 15:38 UTC, mac641 commented on README.md
> -# sotired
I'd keep the heading and adjust it to the repository name

2021-08-31 07:38 UTC, mac641 submitted a review, later dismissed
😄👍🏿

2021-08-31 08:24 UTC, diehmlukas submitted a review, later dismissed

2021-08-31 08:28 UTC, carina-str reviewed
just a few grammatical improvments, as far as I can tell

```
soTired is an application for cognitive fatigue assessment.
It includes a stand-alone Android-App for fatigue detection and **an additional part** for data management and further analysis.
The project is structured in a client side (stand-alone App) implemented in Dart/Flutter and a server side (data management) in Golang.
Dart/Flutter **provides** the possibility to simply add an **iOS, Android** and / or Web-Application.
```

2021-08-31 08:30 UTC, treilik reviewed
please add a section for contributions, in which the code tags: "FIXME", "TODO" and "NOTE" are mentioned.

2021-08-31 08:56 UTC, mac641 requested changes
I've added some suggestions, you've previously introduced to me 😁

2021-08-31 08:56 UTC, mac641 commented on README.md
> +It includes a stand-alone Android-App for fatigue detection and an additional part for data management and further analysis.
```suggestion
It includes a stand-alone Android app for fatigue detection and an additional part for data management and further analysis.
```

2021-08-31 08:56 UTC, mac641 commented on README.md
> +The project is structured in a client side (stand-alone App) implemented in Dart/Flutter and a server side (data management) in Golang.
```suggestion
The project is structured as client side (stand-alone app) implemented in Dart/Flutter and a server side (data management) written in Golang.
```

2021-08-31 08:56 UTC, mac641 commented on README.md
> +Dart/Flutter provide the possibility to simply add an iOS and / or Web-Application.
```suggestion
Dart/Flutter provides the ability to simply add an iOS, desktop and / or web application besides Android.
```

2021-08-31 08:56 UTC, mac641 commented on README.md
> +soTired is a remake of the application presented in the [Validation of a Smartphone-Based Approach to In Situ Cognitive Fatigue Assessment](https://mhealth.jmir.org/2017/8/e125) paper by Edward Price
```suggestion
soTired is a rewrite of the application presented in the [Validation of a Smartphone-Based Approach to In Situ Cognitive Fatigue Assessment](https://mhealth.jmir.org/2017/8/e125) paper by Edward Price, George Moore, Leo Galway and Mark Linden.
```

2021-08-31 09:03 UTC, closed without merging