Issue/70 scheduler notification
teamulster2/soTired pull request #71
Opened 2021-09-15 14:17 UTC by diehmlukas

Changed interval notification to a notification who is shown to a specific time.
On the config can with help of a list different times be adjusted.

close #70

2021-09-15 15:18 UTC, mac641 requested changes
I think, I have to request this tiny readability improvement but other than that it looks good to me. 🎉

2021-09-15 15:18 UTC, mac641 commented on app/lib/notifications.dart
>  import 'package:timezone/timezone.dart' as tz;
```suggestion
import 'package:timezone/timezone.dart';
```

You might want to remove `tz` in this file to make our source code less sophisticated.

2021-09-16 07:42 UTC, AnnaGsell approved these changes

2021-09-16 07:45 UTC, mac641 approved these changes
I like, I like 👍🏿

2021-09-16 07:46 UTC, merged